In [1]:
import pandas as pd
import math

In [2]:
dfInfo = pd.read_excel("stat.xlsx", 0)
dfAtk = pd.read_excel("stat.xlsx", 1)
dfScal = pd.read_excel("stat.xlsx", 2)
dfCalcCorrectId = pd.read_excel("stat.xlsx", 3)
dfAttackElementCorrect = pd.read_excel("stat.xlsx", 4)
dfCoef = pd.read_excel("stat.xlsx", 5)
dfStat = pd.read_excel("stat.xlsx", 6)

In [3]:
dfInfo.head()

,Name,Weapon Name,Affinity (Dropdown),Affinity,Max Upgrade,Required (Str),Required (Dex),Required (Int),Required (Fai),Required (Arc),Physical Damage Type,Weight,Weapon Type,2H Str Bonus,Reinforce Type ID
0,Dagger,Dagger,None,None,25,5,9,0,0,0,Slash/Pierce,1.5,Dagger,Yes,0
1,Heavy Dagger,Dagger,Heavy,Heavy,25,5,9,0,0,0,Slash/Pierce,1.5,Dagger,Yes,100
2,Keen Dagger,Dagger,Keen,Keen,25,5,9,0,0,0,Slash/Pierce,1.5,Dagger,Yes,5000
3,Quality Dagger,Dagger,Quality,Quality,25,5,9,0,0,0,Slash/Pierce,1.5,Dagger,Yes,300
4,Fire Dagger,Dagger,Fire,Fire,25,5,9,0,0,0,Slash/Pierce,1.5,Dagger,Yes,400

In [4]:
dfAtk.head()

,Name,Phys0,Mag0,Fire0,Ligh0,Holy0,Stam0,Phys1,Mag1,Fire1,...,Fire24,Ligh24,Holy24,Stam24,Phys25,Mag25,Fire25,Ligh25,Holy25,Stam25
0,Dagger,74.00,0.0,0.0,0.0,0.0,30.0,78.292,0.0,0.000,...,0.000,0.0,0.0,58.8,181.30,0.0,0.0,0.0,0.0,60.0
1,Heavy Dagger,67.45,0.0,0.0,0.0,0.0,30.0,71.426,0.0,0.000,...,0.000,0.0,0.0,58.8,166.85,0.0,0.0,0.0,0.0,60.0
2,Keen Dagger,67.45,0.0,0.0,0.0,0.0,28.5,71.000,0.0,0.000,...,0.000,0.0,0.0,64.5,156.20,0.0,0.0,0.0,0.0,66.0
3,Quality Dagger,63.90,0.0,0.0,0.0,0.0,30.0,67.166,0.0,0.000,...,0.000,0.0,0.0,58.8,145.55,0.0,0.0,0.0,0.0,60.0
4,Fire Dagger,56.80,0.0,56.8,0.0,0.0,30.0,59.356,0.0,59.356,...,118.144,0.0,0.0,58.8,120.70,0.0,120.7,0.0,0.0,60.0

In [5]:
dfScal.head()

,Name,Str0,Dex0,Int0,Fai0,Arc0,Str1,Dex1,Int1,Fai1,...,Str24,Dex24,Int24,Fai24,Arc24,Str25,Dex25,Int25,Fai25,Arc25
0,Dagger,0.350,0.65,0.0,0.0,0.0,0.3570,0.6630,0.0,0.0,...,0.5180,0.9620,0.0,0.0,0.0,0.525,0.975,0.0,0.0,0.0
1,Heavy Dagger,0.990,0.00,0.0,0.0,0.0,1.0175,0.0000,0.0,0.0,...,1.5290,0.0000,0.0,0.0,0.0,1.540,0.000,0.0,0.0,0.0
2,Keen Dagger,0.100,1.05,0.0,0.0,0.0,0.1060,1.0850,0.0,0.0,...,0.2560,1.7360,0.0,0.0,0.0,0.260,1.750,0.0,0.0,0.0
3,Quality Dagger,0.630,0.63,0.0,0.0,0.0,0.6615,0.6615,0.0,0.0,...,1.1844,1.1844,0.0,0.0,0.0,1.197,1.197,0.0,0.0,0.0
4,Fire Dagger,0.611,0.05,0.0,0.0,0.0,0.6298,0.0530,0.0,0.0,...,0.9776,0.1180,0.0,0.0,0.0,0.987,0.120,0.0,0.0,0.0

In [6]:
dfCalcCorrectId.head()

             Name  Phys  Mag  Fire  Ligh  Holy  AttackElementCorrectId
0          Dagger     0    0     0     0     0                   10000
1    Heavy Dagger     1    0     0     0     0                   10000
2     Keen Dagger     2    0     0     0     0                   10000
3  Quality Dagger     8    0     0     0     0                   10000
4     Fire Dagger     0    0     4     0     0                   10005

In [7]:
dfAttackElementCorrect.head()

,AttackElementCorrectParamId,Str/Phys,Dex/Phys,Int/Phys,Fai/Phys,Arc/Phys,Str/Mag,Dex/Mag,Int/Mag,Fai/Mag,...,Str/Ligh,Dex/Ligh,Int/Ligh,Fai/Ligh,Arc/Ligh,Str/Holy,Dex/Holy,Int/Holy,Fai/Holy,Arc/Holy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,1000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1001,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
4,1002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [8]:
dfCoef.head()

,CalcCorrectId,LevelCap1,LevelCap2,LevelCap3,Add1,Add2,Add3,Multiply1,Multiply2,Multiply3,Multiply4,Divide1,Divide2,Divide3,Divide4,Coef1,Coef2,Coef3
0,0,80,60,18,90,75,25,20,15,50,25,70,20,42,17,0,-1,1.2
1,1,80,60,20,90,75,35,20,15,40,35,70,20,40,19,0,-1,1.2
2,2,80,60,20,90,75,35,20,15,40,35,70,20,40,19,0,-1,1.2
3,4,80,50,20,95,80,40,5,15,40,40,19,30,30,19,-1,1,1.0
4,7,80,60,20,90,75,35,20,15,40,35,70,20,40,19,0,-1,1.2

In [9]:
dfStat.head()

   Lvl   HP  FP  Stamina  EquipLoad
0    1  300  40       80       45.0
1    2  304  43       81       45.0
2    3  312  46       83       45.0
3    4  322  49       85       45.0
4    5  334  52       87       45.0

In [10]:
def getRequirement(weapon, statType):
    return dfInfo.loc[dfInfo["Name"] == weapon, "Required (" + statType +")"].to_numpy()[0]
       
def getFlatDamageValue(weapon, damageType, upgradeLevel):
    return dfAtk.loc[dfAtk["Name"] == weapon, damageType + str(upgradeLevel)].to_numpy()[0]
    
def getScalDamageValue(weapon, statType, upgradeLevel):
    return dfScal.loc[dfScal["Name"] == weapon, statType + str(upgradeLevel)].to_numpy()[0]
    
def getCalcCorrectId(weapon, damageType):
    return dfCalcCorrectId.loc[dfCalcCorrectId["Name"] == weapon, damageType].to_numpy()[0]
    
def getCoef(calcCorrectId, coefType):
    return dfCoef.loc[dfCoef["CalcCorrectId"] == calcCorrectId, coefType].to_numpy()[0]
    
def getStat(statType, level):
    return dfStat.loc[dfStat["Lvl"] == level, statType].to_numpy()[0]
    
def getAttackElementCorrectId(weapon):
    return dfCalcCorrectId.loc[dfCalcCorrectId["Name"] == weapon, "AttackElementCorrectId"].to_numpy()[0]
    
def isScaling(weapon, statType, damageType):
    return (dfAttackElementCorrect.loc[dfAttackElementCorrect["AttackElementCorrectParamId"] == getAttackElementCorrectId(weapon), statType + "/" + damageType].to_numpy()[0]) == 1
    
def isRequirementMet(weapon, statType, damageType, lvl):
    return not(isScaling(weapon, statType, damageType) and getRequirement(weapon, statType) > lvl)
    
def getCalcCorrectValue(weapon, statType, damageType, lvl):
    calcCorrectId = getCalcCorrectId(weapon, damageType)
    if isScaling(weapon, statType, damageType):
        if lvl > getCoef(calcCorrectId, "LevelCap1"):
            return getCoef(calcCorrectId, "Add1") + (getCoef(calcCorrectId, "Multiply1")*(lvl - getCoef(calcCorrectId, "LevelCap1"))/getCoef(calcCorrectId, "Divide1"))
        elif lvl > getCoef(calcCorrectId, "LevelCap2"):
            return getCoef(calcCorrectId, "Add2") + (getCoef(calcCorrectId, "Multiply2")*(lvl - getCoef(calcCorrectId, "LevelCap2"))/getCoef(calcCorrectId, "Divide2"))
        elif lvl > getCoef(calcCorrectId, "LevelCap3"):
            return getCoef(calcCorrectId, "Add3") + (getCoef(calcCorrectId, "Multiply3")*(1 + getCoef(calcCorrectId, "Coef1") + getCoef(calcCorrectId, "Coef2")*(1 + getCoef(calcCorrectId, "Coef1") + getCoef(calcCorrectId, "Coef2")*(lvl-getCoef(calcCorrectId, "LevelCap3"))/getCoef(calcCorrectId, "Divide3"))**getCoef(calcCorrectId, "Coef3")))
        else:
            return getCoef(calcCorrectId, "Multiply4")*((lvl - 1)/getCoef(calcCorrectId, "Divide4"))**getCoef(calcCorrectId, "Coef3")
    else :
        return 0
    
def scalingElementDamage(weapon, statType, damageType, upgradeLevel, lvl):
    return getFlatDamageValue(weapon, damageType, upgradeLevel) * getScalDamageValue(weapon, statType, upgradeLevel) * getCalcCorrectValue(weapon, statType, damageType, lvl) / 100

    
def getScalingDamage(weapon, damageType, upgradeLevel, statsLvl):
    listStats = ["Str", "Dex", "Int", "Fai", "Arc"]
    switcher={"Str":0, "Dex":1, "Int":2, "Fai":3, "Arc":4}
    damage = 0
    for stat in listStats:
        if isRequirementMet(weapon, stat, damageType, statsLvl[switcher.get(stat)]):
            damage += scalingElementDamage(weapon, stat, damageType, upgradeLevel, statsLvl[switcher.get(stat)])
        else:
            return -0.4 * getFlatDamageValue(weapon, damageType, upgradeLevel)
        
    return damage
    
def getStatDefense(runeLevel, level):
    if runeLevel <= 71:
        defense = 40 + 60 * ((runeLevel + 79 - 1) / 149)
    elif runeLevel <= 91:
        defense = 100 + 20 * ((runeLevel + 79 - 150) / 20)
    elif runeLevel <= 161:
        defense = 120 + 15 * ((runeLevel + 79 - 170) / 70)
    else:
        defense = 135 + 20 * ((runeLevel + 79 - 240) / 552)
    if level <= 30:
        defense += 10*(level / 30)
    elif runeLevel <= 40:
        defense += 10 + 5 * ((level - 30) / 10)
    elif runeLevel <= 60:
        defense += 15 + 15 * ((level - 40) / 20)
    else:
        defense += 30 + 10 * ((level - 60) / 39)
    return math.floor(defense)
    
def getStatResistance(runeLevel, level):
    if (runeLevel <= 71 ):
        defense = 75 + 30 * ((runeLevel + 79 - 1) / 149)
    elif(runeLevel <= 111 ):
        defense = 105 + 40 * ((runeLevel + 79 - 150) / 40)
    elif(runeLevel <= 161 ):
        defense = 145 + 15 * ((runeLevel + 79 - 190) / 50)
    else:
        defense = 160 + 20 * ((runeLevel + 79 - 240) / 552)
    if level <= 30 :
        defense += 0
    elif(runeLevel <= 40 ):
        defense += 30 * ((level - 30) / 10)
    elif runeLevel <= 60 :
        defense += 30 + 10 * ((level - 40) / 20)
    else:
        defense += 40 + 10 * ((level - 60) / 39)
    return math.floor(defense)

In [11]:
class Build:    
    def __init__(self, weapon, upgradeLevel, vigor, mind, endurance, strength, dexterity, intelligence, faith, arcane):
        self.physFlatDamage = math.floor(getFlatDamageValue(weapon, "Phys", upgradeLevel))
        self.magFlatDamage = math.floor(getFlatDamageValue(weapon, "Mag", upgradeLevel))
        self.fireFlatDamage = math.floor(getFlatDamageValue(weapon, "Fire", upgradeLevel))
        self.lighFlatDamage = math.floor(getFlatDamageValue(weapon, "Ligh", upgradeLevel))
        self.holyFlatDamage = math.floor(getFlatDamageValue(weapon, "Holy", upgradeLevel))
        self.physScalDamage = math.floor(getScalingDamage(weapon, "Phys", upgradeLevel, [strength, dexterity, intelligence, faith, arcane]))
        self.magScalDamage = math.floor(getScalingDamage(weapon, "Mag", upgradeLevel, [strength, dexterity, intelligence, faith, arcane]))
        self.fireScalDamage = math.floor(getScalingDamage(weapon, "Fire", upgradeLevel, [strength, dexterity, intelligence, faith, arcane]))
        self.lighScalDamage = math.floor(getScalingDamage(weapon, "Ligh", upgradeLevel, [strength, dexterity, intelligence, faith, arcane]))
        self.holyScalDamage = math.floor(getScalingDamage(weapon, "Holy", upgradeLevel, [strength, dexterity, intelligence, faith, arcane]))
        self.runeLevel = -79 + vigor + mind + endurance + strength + dexterity + intelligence + faith + arcane
        self.HP = getStat("HP", vigor)
        self.FP = getStat("FP", mind)
        self.stamina = getStat("Stamina", endurance)
        self.equipLoad = getStat("EquipLoad", endurance)
        self.physicalDefense = getStatDefense(self.runeLevel, strength)
        self.magicDefense = getStatDefense(self.runeLevel, intelligence)
        self.fireDefense = getStatDefense(self.runeLevel, vigor)
        self.lightningDefense = getStatDefense(self.runeLevel, 0)
        self.holyDefense = getStatDefense(self.runeLevel, arcane)
        self.immunity = getStatResistance(self.runeLevel, vigor)
        self.robustness = getStatResistance(self.runeLevel, endurance)
        self.focus = getStatResistance(self.runeLevel, mind)
        self.vitality = getStatResistance(self.runeLevel, arcane)

In [12]:
build = Build("Rivers of Blood", 10, 99, 99, 99, 99, 99, 99, 99, 99)

print(build.physFlatDamage)         
print(build.magFlatDamage)
print(build.fireFlatDamage)
print(build.lighFlatDamage)
print(build.holyFlatDamage)
print(build.physScalDamage)
print(build.magScalDamage)
print(build.fireScalDamage)
print(build.lighScalDamage)
print(build.holyScalDamage)

print(build.HP)
print(build.FP)
print(build.stamina)
print(build.equipLoad)
print(build.physicalDefense)
print(build.magicDefense)
print(build.fireDefense)
print(build.lightningDefense)
print(build.holyDefense)
print(build.immunity)
print(build.robustness)
print(build.focus)
print(build.vitality)

186
0
186
0
0
297
0
110
0
0
2100
450
170
160.0
195
195
195
155
195
230
230
230
230